name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version/commit
  - type: textarea
    id: artifacts
    attributes:
      label: Relevant artifacts (`report.md`, `findings.json`)
