name: Repository support request
description: Request support for a new stack/pattern
labels: [support-request]
body:
  - type: textarea
    id: stack
    attributes:
      label: Repository stack
      description: Frameworks, test tools, and project layout
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Representative files
      description: Paths to routes/services/tests
    validations:
      required: true
